spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://36.41.187.107:3306/spring_security?useUnicode=yes&characterEncoding=utf-8&useSSL=false
    username: root
    password: Ywm@mysql36
  session:
    store-type: none
security:
  basic:
    enabled: false
server:
  port: 8060

#jerry:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

jerry:
  security:
    browser:
      loginType: REDIRECT